baseURL = "https://heuristic-snyder-2d4b60.netlify.com/"
languageCode = "en-us"
title = "Kenneth McCullers"
theme = "code"
disqusShortname = "kenneth-mccullers-1"

[params]
	custom_css = ["css/custom.css"]

# Menu Links
[[menu.main]]
	name = "About"
	weight = 1
	url = "/about/"

[[menu.main]]
	name = "Portfolio"
	weight = 2
	url = "/portfolio/"

[[menu.main]]
	name = "Blog"
	weight = 3
	url = "/posts/"

[[menu.main]]
	name = "Contact"
	weight = 4
	url = "/contact/"
